# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: '(.idea|node_modules|.tox)'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-builtin-literals
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-toml
      - id: fix-encoding-pragma
        args:
          - --remove
  - repo: https://github.com/timothycrosley/isort
    rev: '4.3.21'
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.0a2
    hooks:
      - id: flake8
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.2.1
    hooks:
      - id: pyupgrade
        args:
          - --py3-plus
  - repo: local
    hooks:
      - id: towncrier
        name: towncrier
        entry: inv towncrier-check
        language: system
        pass_filenames: false
        always_run: true
